### ISSUE TITLE
gameobj-data.xml - clothing additions

### ISSUE THREAD

**Issue by Vyrshkana** [elanthia-online/scripts#44]
I have no idea how to do a pull request, especially given that my gameobj-data.xml has a ton of stuff changed and I'm only listing one set of rule additions per issue.  Please forgive the uneducated report.

These were added to my gameobj-data.xml file while going through ~40 characters' inventories, as well as past merchant event shop listings.

Addition to clothing <nouns>:
|stole|corset|calf\-boots|eyepatch|bandolier|gauntlets|thigh\-quiver|ruff|mask|apron|half\-gloves|hip\-satchel|overskirt|belts|greatkilt|sporran|sark|capelet|pelisse|waistcoat|veil|handwarmer|cravat|hosen|bowtie|houppelande|neckpouch|thigh\-sheath|overgown|knee\-boots|apotla|apotl|ataniki|bliaut|loincloth|petticoat|rucksack|sundress|cotehardie|manteau|chopines|headwrap|half\-cloak|back\-scabbard|nightdress|jerkin|buckskins|moccasins|hip\-pouch|sweater|beret|hip\-scarf

**Comment by sandersch** [comment]
I just merged #43 to add tests for the existing entries, so we are in a good spot to add more. Quick scan through the additions here looks reasonable. One potential issue is that some of these might be ambiguous between multiple types (e.g. jerkin is an [approved armor noun](https://gswiki.play.net/List_of_alternative_armor_names)). Clothing vs armor are probably the least consequential types to mix up, but want to get them right wherever possible.

Do you have full name examples for these? Where possible, I am trying to add specific examples for entries in the gameobj-data. Not a big deal if you don't have them handy, but adding them would make it easier to get the types right for ambiguous nouns and to avoid breaking things in the future.

**Comment by Vyrshkana** [comment]
I went and sourced close to all of them (and found a lot of others).  Went ahead and removed both jerkin and gauntlets for clothing and armor conflicts.  Gauntlet COULD, technically, be a weapon given that the spirit bows are physically speaking single gauntlets, but that's exceedingly rare and, well, it's still a piece of clothing.

The few that are still missing a source item I'm still working on tracking down, but given my gameobj-data's been modified over the course of about 20 months I can't make promises.

ankle-boots	-	a pair of white suede ankle-boots
ankle-sheath	-	a plain black leather ankle-sheath with tiny brass buckles
apotl	-	a sleek black feathered apotl
apotla	-	a rustic cocoa suede apotla adorned with tawny owl feathers
apron	-	a colorful twine-stitched apron of patchwork fabric
arm-wraps	-	a set of layered brown leather arm-wraps
ataniki	-	a twilight blue damask ataniki lined with moonlight silver velvet
atiki	-	a deep green silk atiki
back-scabbard	-	
baldric	-	a sturdy vruul skin baldric set with a vaalin toggle
bandolier	-	a pale blue leather bandolier trimmed with faenor thread
belts	-	
beret	-	a gold whip-stitched scarlet satin beret
biretta	-	an argent and ivory silk biretta
bliaut	-	a silver-shot white samite bliaut
bowtie	-	
breechcloth	-	a long golden silk breechcloth reinforced with a thick muslin lining
buckskins	-	a pair of dun buckskins with a patch on one knee
burnoose	-	a heavy yierka-hide burnoose
caban	-	a silver-worked dark green caban with buttoned sleeves 
calf-boots	-	some soft black suede calf-boots
capelet	-	a white-feathered capelet with a curvilinear asp fetish pin
carryall	-	a patchwork snakeskin carryall with a corded sinew drawstring
chaperon	-	a storm grey velvet chaperon with pewter-hued embroidery
chasuble	-	a flowing taupe chasuble with a gilt-embroidered cowl collar
chopines	-	a pair of rigid bronzed raw silk chopines
cincher	-	a mottled black viper skin cincher 
cope	-	a long niveous moire cope edged in sapphire-hued embroidery
corset	-	an onyx-traced pewter flyrsilk corset
cotehardie	-	a short and fitted dark cerulean cotehardie
cravat	-	a perforated ivory leather cravat
dolman	-	an emerald silk dolman with layered floor-length sleeves
eyepatch	-	a skull-stamped black leather eyepatch
face-veil	-	a crimson silk face-veil
gauntlet	-	a leather-lined steel plate gauntlet
greatcoat	-	a bronze-traced henna leather greatcoat with narrow lapels
greatkilt	-	a green and claret wool greatkilt pinned with a copper lion
guard	-	a sturdy brown leather wrist guard etched with a dragonfly
habit	-	a coarse brown wool habit
hair-wrap	-	a tightly wound black cotton hair-wrap
half-bodice	-	a pale linen half-bodice with viridian knotwork embroidery
half-boots	-	a pair of cuffed charcoal leather half-boots
half-cape	-	a hooded pale apricot half-cape
half-cloak	-	an umber gauze half-cloak
half-gloves	-	some onyx-clawed dark leather half-gloves
half-mask	-	a shadowy grey suede half-mask
handwarmer	-	
headdress	-	a headdress of emerald and ruby tailfeathers
headscarf	-	a silver-dagged royal blue headscarf
headwrap	-	a bright red cotton headwrap
henin	-	a pale gossamer-veiled henin
hip-basket	-	a braided sweetgrass hip-basket
hip-belt	-	a sapphire and silver hip-belt
hip-jacket	-	a brushed ebon suede hip-jacket with mithglin buttons
hip-pouch	-	an oversized black leather hip-pouch
hip-quiver	-	a silver silk-lined brown leather hip-quiver
hip-satchel	-	a sturdy sorrel leather hip-satchel
hip-scarf	-	a triangular turquoise silk hip-scarf edged with bronze bells
hose	-	a pair of sheer argent hose
hosen	-	some golden hosen of satin silk
houppelande	-	a dark mahogany cotton houppelande with fawn pinstripes
isiqiri	-	a dark bronze silk isiqiri
kanjiqi	-	a shadowed green silk kanjiqi
kanjir	-	some russet silk kanjir with a shell-carved dream agate accent
knee-boots	-	some hunter green suede knee-boots
knee-breeches	-	a pair of fitted black leather knee-breeches
leg-wraps	-	a pair of raw linen leg-wraps secured with leather cords
loincloth	-	a dark leather loincloth with an elongated front panel
manteau	-	a fawn wool manteau with a gossamer lace costume hood
mantilla	-	an ebon-lined viridian silk mantilla
mask	-	a weeping clown mask
mittens	-	some luxurious mink fur mittens
mitter	-	a conical golden silk mitter
moccasins	-	a pair of vine-laced soft black deerskin moccasins
muff	-	a richly hued muff of plush firecat pelts
nanjir	-	some elegant dark brown silk nanjir
neck-kerchief	-	a red-trimmed black suede neck-kerchief strung with rubies
neckpouch	-	a diminutive brocade neckpouch cinched with a leather thong
nightdress	-	
nightgown	-	a lavender flannel nightgown
nightshirt	-	a roomy plaid flannel nightshirt
overdress	-	an inky black satin overdress beaded with dark jewel droplets
overgown	-	an ivory silk overgown worked with obsidian blossoms
over-robe	-	a sleeveless bright scarlet over-robe beaded with gold agates
overskirt	-	a translucent silver overskirt with contrasting onyx hems
pantaloons	-	some billowy black linen pantaloons
pelisse	-	a raven-colored pelisse shifting with hints of intense lapis
pelisson	-	a layered powder blue pelisson lined with white fur
petticoat	-	a grey silk scallop-hemmed petticoat
reticule	-	a lace-covered dim black linen reticule
rucksack	-	a battered leather rucksack
ruff	-	a tall ebon organza ruff adorned with metallic copper pleating
saephua	-	a royal violet velvet saephua speckled with silver stars
sark	-	
scarves	-	a pair of pale sea blue scarves
shoulder-wrap	-	a fluffy red macaw feather shoulder-wrap
skirts	-	some layered cotton and silk skirts
skullcap	-	a faded leather skullcap
sporran	-	
stockings	-	a pair of pure white stockings
stole	-	a plush ribbed blue-grey chinchilla stole
stomacher	-	a side-buttoned crimson leather stomacher overlaying a gown of ruched saffron silk
sundress	-	an iris-hued sendal sundress edged with a spray of pearls
surcote	-	a rich cranberry gauze surcote belted with copper leaves
surplice	-	a henna-hued marbrinus surplice edged in bronze threading
sweater	-	an ivory cable knit sweater crafted from heavy wool
sword-belt	-	a twice wrapped sharkskin sword-belt
thigh-boots	-	some thin-soled dark leather thigh-boots 
thigh-quiver	-	a feather-tied dark leather thigh-quiver
thigh-sheath	-	a tooled vruul-skin thigh-sheath
tote	-	a gold-threaded brocade tote with a sturdy cord drawstring
trews	-	some high-waisted pomegranate leather trews
tricorn	-	a silk-lined dark lapis suede tricorn set with silver studs
turban	-	a loosely-wrapped veiled turban
undergown	-	a full-length satin undergown boasting a deep rose hue 
underrobe	-	a loose midnight black underrobe with heavily ruched sleeves
vatanura	-	a gold and jade green silk vatanura
veil	-	a lace-edged white silk veil
vestment	-	a hooded crimson satin vestment trimmed in gold threading
waist-cincher	-	a silver-boned malachite suede waist-cincher
waistcoat	-	an ivory cambric waistcoat fettered by birch toggles
waist-sash	-	a wide goat-hide waist-sash
wrap	-	a stunning fox fur wrap with gold nugget toggles
wrap-skirt	-	a sheer blued spidersilk wrap-skirt with a fel-beaded hem
wrist-purse	-	a sunflower-clasped silken wrist-purse
wrist-sheath	-	a gold-stitched green suede wrist-sheath
yatane	-	some distressed leather yatane

**Comment by Vyrshkana** [comment]
LOL man you're going to hate me.  I have another list of clothing nouns for you which I'm still working on.  I'll see if I can't find the nightdress example while I'm at it.

I'll hold off on the jewelry and weapon lists until they're complete.

**Comment by Vyrshkana** [comment]
Here's the nightdress example:

a bright red flannel nightdress

**Comment by sandersch** [comment]
Added nightdress to #47. No problem if you have other nouns to add to the list. I can do a follow up release for Phase 2.

**Comment by sandersch** [comment]
Merged #47 for the first phase of new clothing nouns. It sounds like you will have more clothing nouns to add, so I am going to keep this issue open and you can add them here. If you want to add new nouns for other types, please make a different issue for each type.

Thanks for putting together the nouns and examples. This is really useful for improving the accuracy of the GameObj types.

**Comment by Vyrshkana** [comment]
More clothing nouns.  The last two (gambeson and aketon) I have only seen as clothing but given their meaning possibly maybe could be some kind of light-ish armor?  I haven't come across any though in my research.

shift	-	a crimped azure gauze shift chased in iris-patterned ribbon
clogs	-	a pair of pine clogs with verbena cutouts on the low heels
headscarf	-	a twice-wrapped silk gauze headscarf patterned with lavender
halfboots	-	a pair of small brown suede halfboots
seacoat	-	a salt-stained seacoat
anklepouch	-	a small locksmith's anklepouch
toolpouch	-	a myklian-scale locksmith's toolpouch
toolkit	-	a small ruby-clasped toolkit
wrappings	-	some suede facial wrappings
hip-vest	-	a silver-edged black silk hip-vest
hip-waders	-	some thigh-high leather hip-waders
head-scarf	-	a dark red and pale ivory silk head-scarf
sarong	-	a gold-edged roseate silk sarong
gempouch	-	a cobalt blue silk drawstring gempouch
reticule	-	a matte gold silk drawstring reticule
wimple	-	a lace-trimmed white taffeta wimple 
half-boots	-	some weathered black leather half-boots
raincoat	-	a salmon skin raincoat stitched together by tundra grass
covering	-	a sheer-paneled ebon brocade covering
face-wrap	-	a pearl-limned silvery silk face-wrap
waistpouch	-	a deep sienna waistpouch tied with an ivory chiffon ribbon
handbag	-	an embroidered ivory handbag hemmed in blue lace
hairnet	-	an ebony spidersilk web hairnet with a crimson comb
cotta	-	a white silk cotta traced with a repeating cross pattern 
sunhat	-	a ribbon-tied wide brimmed sunhat
shoulderbag	-	a glittering seashell-edged shoulderbag
windcape	-	a high-collared pitch black windcape
warcape	-	a long black eyeball-print warcape
warcloak	-	a long bronze-pinned warcloak
poulaines	-	a pair of brass-belled poulaines
hair-scarf	-	a pale green linen hair-scarf
knickers	-	some button-up green woolen knickers
bloomers	-	some speckled eggshell silk bloomers
britches	-	a pair of black pinstriped britches
hip-sash	-	a charm-edged thin gold mesh hip-sash
carrier	-	a brilliant ruby-red dagger carrier
cummerbund	-	a wide purple silk cummerbund
shorts	-	some striped blue and white shorts
boater	-	a thick white banded boater
hipsack	-	a wide-mouthed grey leather hipsack branded with a black eye
costume	-	an iridescent sea green bathing costume with a wavy design
paltock	-	a chestnut leather paltock embroidered with gold fretwork 
mitts	-	a pair of thick canvas oven mitts
tricorne	-	a stiff leather coal black tricorne adorned with an elegant plume
backscabbard	-	a brown leather backscabbard
hosiery	-	some opaque off-white hosiery
greatbelt	-	a heavy iron-studded brown suede greatbelt
miter	-	a tall white silk miter embroidered with flowing runes
wraps	-	some soft leather foot wraps
hip-sack	-	a mottled soft leather hip-sack
fichu	-	a beaded emerald silk fichu
cothurns	-	some sienna side-laced cothurns
backsheaths	-	some crossed mithril backsheaths
backsheath	-	a double linked chain backsheath
brat	-	a green and gold brat with an ivory clasp
brogues	-	a pair of soft brogues cobbled from spotted gak hide
ghillies	-	a pair of fine leather ghillies laced with black silk cord
beluque	-	a close-cut silk-lined beluque trimmed with sable fur
muffler	-	an arctic fox fur muffler piped with cobalt-blue silk
chaps	-	some scorched canvas forging chaps with polished invar studs
chausses	-	a pair of heavy cambric chausses
goggles	-	some leather forging goggles with polished glass lenses 
	exception: pair of prismatic goggles (simucoin Reim things)
* gambeson	-	a thick quilted gambeson
* aketon	-	a densely padded aketon
